language: python

python:
  - 2.7

install:
  - wget http://downloads.buildout.org/2/bootstrap.py
  - python bootstrap.py
  - bin/buildout
  - cd src/voteit.core
  - git checkout auth
  - cd ../..

#FIXME: This requires auth branch, until it has been merged, leave this here!

script: bin/py setup.py test -q

